---
- name: start php
  service:
    name: php7.4-fpm
    state: started

- name: reload php
  service:
    name: php7.4-fpm
    state: reloaded

- name: restart php
  service:
    name: php7.4-fpm
    state: restarted